#include "token_type.h"

std::string token_type_repr(TokenType type) {
  switch (type) {
    case TokenType::LEFT_PAREN:
      return "LeftParen";
    case TokenType::RIGHT_PAREN:
      return "RightParen";
    case TokenType::LEFT_BRACE:
      return "LeftBrace";
    case TokenType::RIGHT_BRACE:
      return "RightBrace";
    case TokenType::COMMA:
      return "Comma";
    case TokenType::DOT:
      return "Dot";
    case TokenType::MINUS:
      return "Minus";
    case TokenType::PLUS:
      return "Plus";
    case TokenType::SEMICOLON:
      return "Semicolon";
    case TokenType::SLASH:
      return "Slash";
    case TokenType::STAR:
      return "Star";
    case TokenType::BANG:
      return "Bang";
    case TokenType::BANG_EQUAL:
      return "BangEqual";
    case TokenType::EQUAL:
      return "Equal";
    case TokenType::EQUAL_EQUAL:
      return "EqualEqual";
    case TokenType::GREATER:
      return "Greater";
    case TokenType::GREATER_EQUAL:
      return "GreaterEqual";
    case TokenType::LESS:
      return "Less";
    case TokenType::LESS_EQUAL:
      return "LessEqual";
    case TokenType::IDENTIFIER:
      return "Identifier";
    case TokenType::STRING:
      return "String";
    case TokenType::NUMBER:
      return "Number";
    case TokenType::AND:
      return "And";
    case TokenType::CLASS:
      return "Class";
    case TokenType::ELSE:
      return "Else";
    case TokenType::FALSE:
      return "False";
    case TokenType::FUN:
      return "Fun";
    case TokenType::FOR:
      return "For";
    case TokenType::IF:
      return "If";
    case TokenType::NIL:
      return "Nil";
    case TokenType::OR:
      return "Or";
    case TokenType::PRINT:
      return "Print";
    case TokenType::RETURN:
      return "Return";
    case TokenType::SUPER:
      return "Suoer";
    case TokenType::THIS:
      return "This";
    case TokenType::TRUE:
      return "True";
    case TokenType::VAR:
      return "Var";
    case TokenType::WHILE:
      return "While";
    case TokenType::EOF_:
      return "EOF";
  }
}
